project:
  type: book

book:
  title: "R Computing in Bengali"
  author: "Samrit Pramanik"
  date: "2024-03-20"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/01-basics.qmd
    - chapters/02-data-structures.qmd
    - chapters/03-data-manipulation.qmd
    - chapters/04-data-visualization.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: xelatex
    mainfont: "Kalpurush"
    monofont: "Kalpurush"
    documentclass: scrreprt

editor: visual

